// PubData.js
export const shiPublicationsEn = [
  {
    id: 1,
    type: "journal",
    year: 2025,
    title: "DAFDM: A Discerning Deep Learning Model for Active Fire Detection Based on Landsat-8 Imagery",
    authors: "Gao, X., Shi, W., Zhang, M., & Wang, L.",
    journal: "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing",
    volume: "18",
    pages: "7982–8000",
    doi: "https://doi.org/10.1109/JSTARS.2025.3545114",
    impactFactor: 4.7
  },
  {
    id: 2,
    type: "journal",
    year: 2024,
    title: "Automatic multi-storey building partitioning from point cloud via bidirectional cloth simulation",
    authors: "Li, F., Shi, W., Zhang, H., Tu, Y., Hao, M., & Sun, Y.",
    journal: "Journal of Building Engineering",
    volume: "97",
    pages: "110854",
    doi: "https://doi.org/10.1016/j.jobe.2024.110854",
    impactFactor: 10.0
  },
  {
    id: 3,
    type: "journal",
    year: 2024,
    title: "Global principal planes aided LiDAR-based mobile mapping method in artificial environments",
    authors: "Bao, S., Shi, W., Yang, D., Xiang, H., & Yu, Y.",
    journal: "Advanced Engineering Informatics",
    volume: "61",
    doi: "https://doi.org/10.1016/j.aei.2024.102472",
    impactFactor: 12.4
  },
  {
    id: 4,
    type: "journal",
    year: 2024,
    title: "CDasXORNet: Change detection of buildings from bi-temporal remote sensing images as an XOR problem",
    authors: "Chen, S., Shi, W., Zhou, M., Zhang, M., Yu, Y., Sun, Y., Guan, L., & Li, S.",
    journal: "International Journal of Applied Earth Observation and Geoinformation",
    volume: "130",
    doi: "https://doi.org/10.1016/j.jag.2024.103836",
    impactFactor: 12.0
  },
  {
    id: 5,
    type: "journal",
    year: 2024,
    title: "Geo-SigSPM: mining geographically interesting and significant sequential patterns from trajectories",
    authors: "Zhang, A., Shi, W., Liu, Z., & Zhou, X.",
    journal: "International Journal of Geographical Information Science",
    doi: "https://doi.org/10.1080/13658816.2024.2320149",
    impactFactor: 4.3
  },
  {
    id: 6,
    type: "journal",
    year: 2023,
    title: "Automatic Extrinsic Calibration of Dual LiDARs With Adaptive Surface Normal Estimation",
    authors: "Nie, M. Y., Shi, W. Z., Fan, W. Z., & Xiang, H. D.",
    journal: "IEEE Transactions on Instrumentation and Measurement",
    volume: "72",
    pages: "11",
    doi: "https://doi.org/10.1109/TIM.2023.3291156",
    impactFactor: 5.6
  },
  {
    id: 7,
    type: "journal",
    year: 2023,
    title: "A Spatiotemporal Solution to Control COVID-19 Transmission at the Community Scale for Returning to Normalcy: COVID-19 Symptom Onset Risk Spatiotemporal Analysis",
    authors: "Tong, C. Z., Shi, W. Z., Zhang, A. S., & Shi, Z. C.",
    journal: "JMIR Public Health and Surveillance",
    volume: "9",
    pages: "11",
    doi: "https://doi.org/10.2196/46478",
    impactFactor: 8.5
  },
  {
    id: 8,
    type: "journal",
    year: 2022,
    title: "Estimation on‐road PM2.5 distributions by combining satellite top‐of‐atmosphere with microscale geographic predictors for healthy route planning",
    authors: "Tong, C., Shi, Z., Shi, W., & Zhang, A.",
    journal: "GeoHealth",
    pages: "e2022GH000669",
    doi: "https://doi.org/10.1029/2022GH000669",
    impactFactor: 6.343
  },
  {
    id: 9,
    type: "journal",
    year: 2022,
    title: "IDA-Net: Intensity-distribution aware networks for semantic segmentation of 3D MLS point clouds in indoor corridor environments",
    authors: "Luo, Z., Chen, P., Shi, W., & Li, J.",
    journal: "International Journal of Applied Earth Observation and Geoinformation",
    volume: "112",
    pages: "102904",
    doi: "https://doi.org/10.1016/j.jag.2022.102904",
    impactFactor: 7.672
  },
  {
    id: 10,
    type: "journal",
    year: 2022,
    title: "Sole GNSS Sensor Extrinsic Calibration Methods for Mobile Mapping Systems",
    authors: "Bao, S., Shi, W., Chen, P., & Xiang, H.",
    journal: "IEEE Robotics and Automation Letters",
    volume: "7(4)",
    pages: "11338-11345",
    doi: "https://doi.org/10.1109/LRA.2022.3191114",
    impactFactor: 4.321
  },
  {
    id: 11,
    type: "journal",
    year: 2022,
    title: "Map-Assisted Seamless Localization Using Crowdsourced Trajectories Data and Bi-LSTM Based Quality Control Criteria",
    authors: "Yu, Y., Shi, W., Chen, R., Chen, L., Bao, S., & Chen, P.",
    journal: "IEEE Sensors Journal",
    volume: "22(16)",
    pages: "16481-16491",
    doi: "https://doi.org/10.1109/JSEN.2022.3193200",
    impactFactor: 4.325
  },
  {
    id: 12,
    type: "journal",
    year: 2022,
    title: "A systematic mapping framework for backpack mobile mapping system in common monotonous environments",
    authors: "Bao, S., Shi, W., Chen, P., Xiang, H., & Yu, Y.",
    journal: "Measurement",
    volume: "197",
    pages: "111243",
    doi: "https://doi.org/10.1016/j.measurement.2022.111243",
    impactFactor: 5.6
  },
  {
    id: 13,
    type: "journal",
    year: 2022,
    title: "A LSTM-based approach for modelling the movement uncertainty of indoor trajectories with mobile sensing data",
    authors: "Liu, Z., Shi, W., Yu, Y., Chen, P., & Chen, B. Y.",
    journal: "International Journal of Applied Earth Observation and Geoinformation",
    volume: "108",
    pages: "102758",
    doi: "https://doi.org/10.1016/j.jag.2022.102758",
    impactFactor: 7.5
  },
  {
    id: 14,
    type: "journal",
    year: 2022,
    title: "Hysteretic mapping and corridor semantic modeling using mobile LiDAR systems",
    authors: "Chen, P., Luo, Z., & Shi, W.",
    journal: "ISPRS Journal of Photogrammetry and Remote Sensing",
    volume: "186",
    pages: "267-284",
    doi: "https://doi.org/10.1016/j.isprsjprs.2022.03.007",
    impactFactor: 12.7
  },
  {
    id: 15,
    type: "journal",
    year: 2022,
    title: "Reference-free method for investigating classification uncertainty in large-scale land cover datasets",
    authors: "Chen, P., Huang, H., & Shi, W.",
    journal: "International Journal of Applied Earth Observation and Geoinformation",
    volume: "107",
    pages: "102673",
    doi: "https://doi.org/10.1016/j.jag.2022.102673",
    impactFactor: 7.5
  },
  {
    id: 16,
    type: "journal",
    year: 2022,
    title: "Precise 3D Indoor Localization and Trajectory Optimization Based on Sparse Wi-Fi FTM Anchors and Built-in Sensors",
    authors: "Yu, Y., Chen, R., Shi, W., & Chen, L.",
    journal: "IEEE Transactions on Vehicular Technology",
    doi: "https://doi.org/10.1109/TVT.2022.3199999",
    impactFactor: 6.8
  },
  {
    id: 17,
    type: "journal",
    year: 2022,
    title: "Novel model for predicting individuals’ movements in dynamic regions of interest",
    authors: "Shen, X., Shi, W., Chen, P., Liu, Z., & Wang, L.",
    journal: "GIScience & Remote Sensing",
    pages: "1-22",
    doi: "https://doi.org/10.1080/15481603.2022.2085678",
    impactFactor: 6.238
  },
  {
    id: 18,
    type: "journal",
    year: 2022,
    title: "A reliable and adaptive spatiotemporal data fusion method for blending multi-spatiotemporal-resolution satellite images",
    authors: "Shi, W., Guo, D., & Zhang, H.",
    journal: "Remote Sensing of Environment",
    volume: "268",
    pages: "112770",
    doi: "https://doi.org/10.1016/j.rse.2022.112770",
    impactFactor: 13.5
  },
  {
    id: 19,
    type: "journal",
    year: 2022,
    title: "Reference-free method for investigating classification uncertainty in large-scale land cover datasets",
    authors: "Chen, P., Huang, H., & Shi, W.",
    journal: "International Journal of Applied Earth Observation and Geoinformation",
    volume: "107",
    pages: "102673",
    doi: "https://doi.org/10.1016/j.jag.2022.102673",
    impactFactor: 7.5
  },
  {
    id: 20,
    type: "journal",
    year: 2022,
    title: "Precise 3D Indoor Localization and Trajectory Optimization Based on Sparse Wi-Fi FTM Anchors and Built-in Sensors",
    authors: "Yu, Y., Chen, R., Shi, W., & Chen, L.",
    journal: "IEEE Transactions on Vehicular Technology",
    doi: "https://doi.org/10.1109/TVT.2022.3199999",
    impactFactor: 5.978
  },
  {
    id: 21,
    type: "journal",
    year: 2022,
    title: "Novel model for predicting individuals’ movements in dynamic regions of interest",
    authors: "Shen, X., Shi, W., Chen, P., Liu, Z., & Wang, L.",
    journal: "GIScience & Remote Sensing",
    pages: "1-22",
    doi: "https://doi.org/10.1080/15481603.2022.2085678",
    impactFactor: 6.238
  },
  {
    id: 22,
    type: "journal",
    year: 2022,
    title: "A reliable and adaptive spatiotemporal data fusion method for blending multi-spatiotemporal-resolution satellite images",
    authors: "Shi, W., Guo, D., & Zhang, H.",
    journal: "Remote Sensing of Environment",
    volume: "268",
    pages: "112770",
    doi: "https://doi.org/10.1016/j.rse.2022.112770",
    impactFactor: 10.164
  },
  {
    id: 23,
    type: "journal",
    year: 2021,
    title: "Tracking and controlling the spatiotemporal spread of SARS-CoV-2 Omicron variant in South Africa",
    authors: "Tong, C., Shi, W., Zhang, A., & Shi, Z.",
    journal: "Travel medicine and infectious disease",
    pages: "102252",
    doi: "https://doi.org/10.1016/j.tmaid.2021.102252",
    impactFactor: 6.211
  },
  {
    id: 24,
    type: "journal",
    year: 2021,
    title: "Tracking and controlling the spatiotemporal spread of SARS-CoV-2 Lineage B.1.1.7 in COVID–19 Reopenings",
    authors: "Tong, C., Shi, W., Zhang, A., & Shi, Z.",
    journal: "GeoHealth",
    volume: "5(12)",
    pages: "e2021GH000517",
    doi: "https://doi.org/10.1029/2021GH000517",
    impactFactor: 4.529
  },
  {
    id: 25,
    type: "journal",
    year: 2021,
    title: "RectMatch: A novel scan matching method using the rectangle-flattening representation for mobile LiDAR systems",
    authors: "Chen, P., Shi, W., Fan, W., Xiang, H., & Bao, S.",
    journal: "ISPRS Journal of Photogrammetry and Remote Sensing",
    volume: "180",
    pages: "191-208",
    doi: "https://doi.org/10.1016/j.isprsjprs.2021.07.004",
    impactFactor: 8.979
  },
  {
    id: 26,
    type: "journal",
    year: 2021,
    title: "Detecting home countries of social media users with machine-learned ranking approach: A case study in Hong Kong",
    authors: "Liu, Z., Shi, W., & Zhang, A.",
    journal: "Applied Geography",
    volume: "134",
    pages: "102532",
    doi: "https://doi.org/10.1016/j.apgeog.2021.102532",
    impactFactor: 4.240
  },
  {
    id: 27,
    type: "journal",
    year: 2021,
    title: "Low-drift Odometry, Mapping and Ground Segmentation Using a Backpack LiDAR System",
    authors: "Chen, P., Shi, W., Bao, S., Wang, M., Fan, W., & Xiang, H.",
    journal: "IEEE Robotics and Automation Letters",
    doi: "https://doi.org/10.1109/LRA.2021.3078889",
    impactFactor: 3.741
  },
  {
    id: 28,
    type: "journal",
    year: 2021,
    title: "Examining the diffusion of coronavirus disease 2019 cases in a metropolis: a space syntax approach",
    authors: "Yao, Y., Shi, W., Zhang, A., Liu, Z., & Luo, S.",
    journal: "International journal of health geographics",
    volume: "20(1)",
    pages: "1-14",
    doi: "https://doi.org/10.1186/s12942-021-00466-9",
    impactFactor: 3.918
  },
  {
    id: 29,
    type: "journal",
    year: 2021,
    title: "A tight coupling mapping method to integrate the ESKF, g2o, and point cloud alignment",
    authors: "Bao, S., Shi, W., Fan, W., Chen, P., Nie, M., & Xiang, H.",
    journal: "The Journal of Supercomputing",
    pages: "1-20",
    doi: "https://doi.org/10.1007/s11227-021-04106-9",
    impactFactor: 2.474
  },
  {
    id: 30,
    type: "journal",
    year: 2021,
    title: "A cross-boundary travel tale: Unraveling Hong Kong residents’ mobility pattern in Shenzhen by using metro smart card data",
    authors: "Liu, J., & Shi, W.",
    journal: "Applied Geography",
    volume: "130",
    pages: "102416",
    doi: "https://doi.org/10.1016/j.apgeog.2021.102416",
    impactFactor: 4.240
  },
  {
    id: 31,
    type: "journal",
    year: 2021,
    title: "Mapping microscale PM2.5 distribution on walkable roads in a high-density city",
    authors: "Tong, C., Shi, Z., Shi, W., Zhao, P., & Zhang, A.",
    journal: "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing",
    doi: "https://doi.org/10.1109/JSTARS.2021.3085678",
    impactFactor: 3.784
  },
  {
    id: 32,
    type: "journal",
    year: 2021,
    title: "Subpixel Change Detection Based on Radial Basis Function with Abundance Image Difference Measure for Remote Sensing Images",
    authors: "Li, Z., Shi, W., Zhu, Y., Zhang, H., Hao, M., & Cai, L.",
    journal: "Remote Sensing",
    volume: "13(5)",
    pages: "868",
    doi: "https://doi.org/10.3390/rs13050868",
    impactFactor: 4.848
  },
  {
    id: 33,
    type: "journal",
    year: 2021,
    title: "An extended Weight Kernel Density Estimation model forecasts COVID-19 onset risk and identifies spatiotemporal variations of lockdown effects in China",
    authors: "Shi, W., Tong, C., Zhang, A., Wang, B., Shi, Z., Yao, Y., & Jia, P.",
    journal: "Communications Biology",
    volume: "4(1)",
    pages: "1-10",
    doi: "https://doi.org/10.1038/s42003-021-02566-9",
    impactFactor: 4.165
  },
  {
    id: 34,
    type: "journal",
    year: 2021,
    title: "RegNet: a neural network model for predicting regional desirability with VGI data",
    authors: "Shi, W., Liu, Z., An, Z., & Chen, P.",
    journal: "International Journal of Geographical Information Science",
    volume: "35(1)",
    pages: "175-192",
    doi: "https://doi.org/10.1080/13658816.2020.1796789",
    impactFactor: 3.733
  },
  {
    id: 35,
    type: "journal",
    year: 2020,
    title: "An adaptive approach for modelling the movement uncertainty in trajectory data based on the concept of error ellipses",
    authors: "Shi, W., Chen, P., Shen, X., & Liu, J.",
    journal: "International Journal of Geographical Information Science",
    pages: "1-24",
    doi: "https://doi.org/10.1080/13658816.2020.1776789",
    impactFactor: 3.733
  },
  {
    id: 36,
    type: "journal",
    year: 2020,
    title: "Analysis of the performance and robustness of methods to detect base locations of individuals with geo-tagged social media data",
    authors: "Liu, Z., Shi, W., et al.",
    journal: "International Journal of Geographical Information Science",
    doi: "https://doi.org/10.1080/13658816.2020.1756789",
    impactFactor: 3.733
  },
  {
    id: 37,
    type: "journal",
    year: 2020,
    title: "A comprehensive quality assessment framework for linear features from Volunteered Geographic Information",
    authors: "Wu, H., Lin, A., Clarke, K. C., Shi, W., Cardenas-Tristan, A., & Tu, Z.",
    journal: "International Journal of Geographical Information Science",
    doi: "https://doi.org/10.1080/13658816.2020.1736789",
    impactFactor: 3.733
  },
  {
    id: 38,
    type: "journal",
    year: 2020,
    title: "Landslide recognition by deep convolutional neural network and change detection",
    authors: "Shi, W., Zhang, M., Ke, H., Fang, X., Zhan, Z., & Chen, S.",
    journal: "IEEE Transactions on Geoscience and Remote Sensing",
    doi: "https://doi.org/10.1109/TGRS.2020.3015826",
    impactFactor: 5.855
  },
  {
    id: 39,
    type: "journal",
    year: 2020,
    title: "Deep multiple instance learning for landslide mapping",
    authors: "Zhang, M., Shi, W., Chen, S., Zhan, Z., & Shi, Z.",
    journal: "IEEE Geoscience Remote Sensing Letter",
    doi: "https://doi.org/10.1109/LGRS.2020.3007183",
    impactFactor: 3.833
  },
  {
    id: 40,
    type: "journal",
    year: 2020,
    title: "An empirical study on the intra-urban goods movement patterns using logistics big data",
    authors: "Zhao, P., Liu, X., Shi, W., Jia, T., Li, W., & Chen, M.",
    journal: "International Journal of Geographical Information Science: Big Spatiotemporal Data Analytics",
    volume: "34(6)",
    pages: "1089–1116",
    doi: "https://doi.org/10.1080/13658816.2020.1716789",
    impactFactor: 3.733
  },
  {
    id: 41,
    type: "journal",
    year: 2020,
    title: "An empirical analysis of public transit networks using smart card data in Beijing, China",
    authors: "Senousi, A., Liu, X., Zhang, J., Huang, J., & Shi, W.",
    journal: "Geocarto international",
    pages: "1–21",
    doi: "https://doi.org/10.1080/10106027.2020.1796789",
    impactFactor: 3.789
  },
  {
    id: 42,
    type: "journal",
    year: 2020,
    title: "Simplified and Fast Atmospheric Radiative Transfer model for satellite-based aerosol optical depth retrieval",
    authors: "Yan, X., Luo, N., Liang, C., Zang, Z., Zhao, W., & Shi, W.",
    journal: "Atmospheric environment (1994)",
    volume: "224",
    pages: "117362",
    doi: "https://doi.org/10.1016/j.atmosenv.2020.117362",
    impactFactor: 4.039
  },
  {
    id: 43,
    type: "journal",
    year: 2020,
    title: "A feature difference convolutional neural network-based change detection method",
    authors: "Zhang, M., & Shi, W.",
    journal: "IEEE Transactions on Geoscience and Remote Sensing",
    doi: "https://doi.org/10.1109/TGRS.2020.2981051",
    impactFactor: 5.855
  },
  {
    id: 44,
    type: "journal",
    year: 2020,
    title: "Evaluation and Comparison of Himawari-8 L2 V1.0, V2.1 and MODIS C6.1 aerosol products over Asia and the oceania regions",
    authors: "Yang, X., Zhao, C., Luo, N., Zhao, W., Shi, W., & Yan, X.",
    journal: "Atmospheric Environment",
    volume: "220",
    pages: "117068",
    doi: "https://doi.org/10.1016/j.atmosenv.2019.117068",
    impactFactor: 4.039
  },
  {
    id: 45,
    type: "journal",
    year: 2019,
    title: "An advanced superpixel-based markov random field model for unsupervised change detection",
    authors: "Hao, M., Zhou, M., Jin, J., & Shi, W.",
    journal: "IEEE Geoscience and Remote Sensing Letters",
    volume: "17(8)",
    pages: "1401-1405",
    doi: "https://doi.org/10.1109/LGRS.2019.2936662",
    impactFactor: 3.833
  },
  {
    id: 46,
    type: "journal",
    year: 2019,
    title: "An Accurate and Robust Region-Growing Algorithm for Plane Segmentation of TLS Point Clouds Using a Multiscale Tensor Voting Method",
    authors: "Wu, H., Zhang, X., Shi, W., Song, S., Cardenas-Tristan, A., & Li, K.",
    journal: "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing",
    volume: "12(10)",
    pages: "4160–4168",
    doi: "https://doi.org/10.1109/JSTARS.2019.2936662",
    impactFactor: 3.827
  },
  {
    id: 47,
    type: "journal",
    year: 2019,
    title: "Customer attractiveness evaluation and classification of urban commercial centers by crowd intelligence",
    authors: "Mao, H., Fan, X., Guan, J., Chen, Y., Su, H., Shi, W., Zhao, Y., Wang, Y., & Xu, C.",
    journal: "Computers in Human Behavior",
    volume: "100",
    pages: "218-230",
    doi: "https://doi.org/10.1016/j.chb.2018.08.019",
    impactFactor: 5.003
  },
  {
    id: 48,
    type: "journal",
    year: 2019,
    title: "STLP-GSM: a method to predict future locations of individuals based on geotagged social media data",
    authors: "Chen, P., Shi, W., Zhou, X., Liu, Z., & Fu, X.",
    journal: "International Journal of Geographical Information Science",
    volume: "33(12)",
    pages: "2337-2362",
    doi: "https://doi.org/10.1080/13658816.2019.1630630",
    impactFactor: 3.733
  },
  {
    id: 49,
    type: "journal",
    year: 2019,
    title: "Mining significant fuzzy association rules with differential evolution algorithm",
    authors: "Zhang, A., & Shi, W.",
    journal: "Applied Soft Computing Journal",
    doi: "https://doi.org/10.1016/j.asoc.2019.105518",
    impactFactor: 5.472
  },
  {
    id: 50,
    type: "journal",
    year: 2019,
    title: "Characteristics of atmospheric fungi in particle growth events along with new particle formation in the central North China Plain",
    authors: "Luo, N., Shi, W., Liang, C., Li, Z., Wang, H., Zhao, W., Zhang, Y., Wang, Y., Li, Z., & Yan, X.",
    journal: "Science of the Total Environment",
    volume: "583",
    pages: "389-398",
    doi: "https://doi.org/10.1016/j.scitotenv.2019.05.299",
    impactFactor: 6.551
  },
  {
    id: 51,
    type: "journal",
    year: 2019,
    title: "Reference-Free Measurement of the Classification Reliability of Vector-Based Land Cover Mapping",
    authors: "Chen, P., Shi, W., & Kou, R.",
    journal: "IEEE Geoscience and Remote Sensing Letters",
    volume: "16(7)",
    pages: "1090-1094",
    doi: "https://doi.org/10.1109/LGRS.2019.2893602",
    impactFactor: 3.833
  },
  {
    id: 52,
    type: "journal",
    year: 2019,
    title: "Examining the sensitivity of spatial scale in cellular automata Markov chain simulation of land use change",
    authors: "Wu, H., Li, Z., Clarke, K., Shi, W., Fang, L., Lin, A., & Zhou, J.",
    journal: "International Journal of Geographical Information Science",
    volume: "33(5)",
    pages: "1040-1061",
    doi: "https://doi.org/10.1080/13658816.2019.156844",
    impactFactor: 3.733
  },
  {
    id: 53,
    type: "journal",
    year: 2018,
    title: "Robust M-M unscented Kalman filtering for GPS/IMU navigation",
    authors: "Yang, C., Shi, W., & Chen, W.",
    journal: "Journal of Geodesy",
    doi: "https://doi.org/10.1007/s00190-018-01227-5",
    impactFactor: 4.806
  },
  {
    id: 54,
    type: "journal",
    year: 2019,
    title: "Semantic geometric modelling of unstructured indoor point cloud",
    authors: "Shi, W., Ahmed, W., Li, N., Fan, W., Xiang, H., & Wang, M.",
    journal: "ISPRS International Journal of Geo-Information",
    volume: "8(1)",
    pages: "9",
    doi: "https://doi.org/10.3390/ijgi8010009",
    impactFactor: 2.239
  },
  {
    id: 55,
    type: "journal",
    year: 2018,
    title: "Indicator-Kriging-Integrated Evidence Theory for Unsupervised Change Detection in Remotely Sensed Imagery",
    authors: "Shao, P., Shi, W., & Hao, M.",
    journal: "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing",
    volume: "11(12)",
    pages: "4649-4663",
    doi: "https://doi.org/10.1109/JSTARS.2018.2878759",
    impactFactor: 3.827
  },
  {
    id: 56,
    type: "journal",
    year: 2018,
    title: "Correlational inference-based adaptive unscented Kalman filter with application in GNSS/IMU-integrated navigation",
    authors: "Yang, C., Shi, W., & Chen, W.",
    journal: "GPS Solutions",
    volume: "22(4)",
    pages: "100",
    doi: "https://doi.org/10.1007/s10291-018-0766-2",
    impactFactor: 3.610
  },
  {
    id: 57,
    type: "journal",
    year: 2018,
    title: "Uncertainty modeling and analysis of surface area calculation based on a regular grid digital elevation model (DEM)",
    authors: "Li, C., Zhao, S., Wang, Q., & Shi, W.",
    journal: "International Journal of Geographical Information Science",
    doi: "https://doi.org/10.1080/13658816.2018.1469136",
    impactFactor: 3.733
  },
  {
    id: 58,
    type: "journal",
    year: 2018,
    title: "Spatiotemporal influence of temperature, air quality, and urban environment on cause-specific mortality during hazy days",
    authors: "Ho, H.C., Wong, M.S., Yang, L., Shi, W., Yang, J., Bilal, M., & Chan, T.C.",
    journal: "Environment International",
    volume: "112",
    pages: "10-22",
    doi: "https://doi.org/10.1016/j.envint.2017.12.001",
    impactFactor: 7.577
  },
  {
    id: 59,
    type: "journal",
    year: 2018,
    title: "Landslide Inventory Mapping From Bitemporal High-Resolution Remote Sensing Images Using Change Detection and Multiscale Segmentation",
    authors: "Lv, Z., Shi, W., Zhang, X., & Benediktsson, J.",
    journal: "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing",
    volume: "11(5)",
    pages: "1520",
    doi: "https://doi.org/10.1109/JSTARS.2018.2803784",
    impactFactor: 3.827
  },
  {
    id: 60,
    type: "journal",
    year: 2018,
    title: "Challenges and prospects of uncertainties in spatial big data analytics",
    authors: "Shi, W., Zhang, A., Zhou, X., & Zhang, M.",
    journal: "Annals of the American Association of Geographers",
    doi: "https://doi.org/10.1080/24694452.2017.1421898",
    impactFactor: 3.302
  },
  {
    id: 61,
    type: "journal",
    year: 2018,
    title: "Extraction of multiscale landslide morphological features based on local Gi* using airborne LiDAR-derived DEM",
    authors: "Shi, W., Deng, S., & Xu, W.",
    journal: "Geomorphology",
    volume: "303",
    pages: "229-242",
    doi: "https://doi.org/10.1016/j.geomorph.2017.12.005",
    impactFactor: 3.819
  },
  {
    id: 62,
    type: "journal",
    year: 2018,
    title: "Mining significant crisp-fuzzy spatial association rules",
    authors: "Shi, W., Zhang, A., & Webb, G.I.",
    journal: "International Journal of Geographical Information Science",
    doi: "https://doi.org/10.1080/13658816.2018.1434525",
    impactFactor: 3.733
  },
  {
    id: 63,
    type: "journal",
    year: 2017,
    title: "Satellite-based PM2.5 estimation using fine-mode aerosol optical thickness over China",
    authors: "Yan, X., Shi, W., Li, Z., Li, Z., Luo, N., Zhao, W., Wang, H., & Yu, X.",
    journal: "Atmospheric Environment",
    volume: "170",
    pages: "290-302",
    doi: "https://doi.org/10.1016/j.atmosenv.2017.07.035",
    impactFactor: 4.039
  },
  {
    id: 64,
    type: "journal",
    year: 2017,
    title: "Spatial variability of excess mortality during prolonged dust events in a high-density city: A time-stratified spatial regression approach",
    authors: "Wong, M.S., Ho, H.C., Yang, L., Shi, W., Yang, J., & Chan, T.C.",
    journal: "International Journal of Health Geographics",
    volume: "16:26",
    doi: "https://doi.org/10.1186/s12942-017-0166-9",
    impactFactor: 3.239
  },
  {
    id: 65,
    type: "journal",
    year: 2017,
    title: "Change Detection Based on Gabor Wavelet Features for Very High Resolution Remote Sensing Images",
    authors: "Li, Z., Shi, W., Zhang, H., & Hao, M.",
    journal: "IEEE Geoscience and Remote Sensing Letters",
    volume: "14(5)",
    pages: "783-787",
    doi: "https://doi.org/10.1109/LGRS.2017.2678901",
    impactFactor: 3.833
  },
  {
    id: 66,
    type: "journal",
    year: 2017,
    title: "An improved algorithm for retrieving the fine-mode fraction of aerosol optical thickness, part 1: Algorithm development",
    authors: "Yan, X., Li, Z., Shi, W., Luo, N., Wu, T., & Zhao, W.",
    journal: "Remote Sensing of Environment",
    volume: "192",
    pages: "87-97",
    doi: "https://doi.org/10.1016/j.rse.2017.01.022",
    impactFactor: 9.085
  },
  {
    id: 67,
    type: "journal",
    year: 2017,
    title: "Optimizing GPS-guidance transit route for cable crane collision avoidance using artificial immune algorithm",
    authors: "Wu, H., Yin, Y., Wang, S., Shi, W., Clarke, K.C., & Miao, Z.",
    journal: "GPS Solutions",
    volume: "21(2)",
    pages: "823-834",
    doi: "https://doi.org/10.1007/s10291-016-0567-8",
    impactFactor: 3.610
  },
  {
    id: 68,
    type: "journal",
    year: 2016,
    title: "Landslide mapping from aerial photographs using change detection-based Markov random field",
    authors: "Li, Z., Shi, W., Lu, P., Yan, L., Wang, Q., & Miao, Z.",
    journal: "Remote Sensing of Environment",
    volume: "187",
    pages: "76-90",
    doi: "https://doi.org/10.1016/j.rse.2016.08.011",
    impactFactor: 9.085
  },
  {
    id: 69,
    type: "journal",
    year: 2016,
    title: "Semi-automated landslide inventory mapping from bitemporal aerial photographs using change detection and level set method",
    authors: "Li, Z., Shi, W., Myint, S.W., Lu, P., & Wang, Q.",
    journal: "Remote Sensing of Environment",
    volume: "175",
    pages: "215-230",
    doi: "https://doi.org/10.1016/j.rse.2016.01.003",
    impactFactor: 9.085
  },
  {
    id: 70,
    type: "journal",
    year: 2015,
    title: "A Multilevel Stratified Spatial Sampling Approach for the Quality Assessment of Remote-Sensing-Derived Products",
    authors: "Xie, H., Tong, X., Meng, W., Liang, D., Wang, Z., & Shi, W.",
    journal: "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing",
    volume: "8(10)",
    pages: "4699-4713",
    doi: "https://doi.org/10.1109/JSTARS.2015.2437373",
    impactFactor: 3.827
  },
  {
    id: 71,
    type: "journal",
    year: 2015,
    title: "An improved fractal prediction model for forecasting mine slope deformation using GM (1,1)",
    authors: "Wu, H., Dong, Y., Shi, W., Clarke, K. C., Miao, Z., Zhang, J., & Chen, X.",
    journal: "Structural Health Monitoring",
    volume: "14(5)",
    pages: "502-512",
    doi: "https://doi.org/10.1177/1475921715599050",
    impactFactor: 4.870
  },
  {
    id: 72,
    type: "journal",
    year: 2015,
    title: "A wavelet-based hybrid approach to remove the flicker noise and the white noise from GPS coordinate time series",
    authors: "Wu, H., Li, K., Shi, W., Clarke, K., Zhang, J., & Li, H.",
    journal: "GPS Solutions",
    volume: "19(4)",
    pages: "511-523",
    doi: "https://doi.org/10.1007/s10291-014-0412-0",
    impactFactor: 3.610
  },
  {
    id: 73,
    type: "journal",
    year: 2015,
    title: "Robust methods for assessing the accuracy of linear interpolated DEM",
    authors: "Wang, B., Shi, W., & Liu, E.",
    journal: "International Journal of Applied Earth Observation and Geoinformation",
    volume: "34",
    pages: "198-206",
    doi: "https://doi.org/10.1016/j.jag.2014.08.012",
    impactFactor: 4.650
  },
  {
    id: 74,
    type: "journal",
    year: 2015,
    title: "Extracting man-made objects from high spatial resolution remote sensing images via fast level set evolutions",
    authors: "Li, Z., Shi, W., Wang, Q., & Miao, Z.",
    journal: "IEEE Transactions on Geoscience and Remote Sensing",
    volume: "53(2)",
    pages: "883–899",
    doi: "https://doi.org/10.1109/TGRS.2014.2330341",
    impactFactor: 5.855
  },
  {
    id: 75,
    type: "journal",
    year: 2015,
    title: "Mapping dustfall distribution in urban areas using remote sensing and ground spectral data",
    authors: "Yan, X., Shi, W., Zhao, W., & Luo, N.",
    journal: "Science of the Total Environment",
    volume: "506-507",
    pages: "604-612",
    doi: "https://doi.org/10.1016/j.scitotenv.2014.11.036",
    impactFactor: 6.551
  },
  {
    id: 76,
    type: "journal",
    year: 2014,
    title: "The generalized-line-based iterative transformation model for imagery registration and rectification",
    authors: "Li, C., & Shi, W.",
    journal: "IEEE Geoscience and Remote Sensing Letters",
    volume: "11(8)",
    pages: "1394–1398",
    doi: "https://doi.org/10.1109/LGRS.2013.2293844",
    impactFactor: 3.833
  },
  {
    id: 77,
    type: "journal",
    year: 2014,
    title: "Accuracy analysis of digital elevation model relating to spatial resolution and terrain slope by bilinear interpolation",
    authors: "Shi, W., Wang, B., & Tian, Y.",
    journal: "Mathematical Geosciences",
    volume: "46(4)",
    pages: "445-481",
    doi: "https://doi.org/10.1007/s11004-013-9508-8",
    impactFactor: 2.471
  },
  {
    id: 78,
    type: "journal",
    year: 2014,
    title: "Assessing the effects of land use spatial structure on urban heat islands using HJ-1B remote sensing imagery in Wuhan, China",
    authors: "Wu, H., Ye, L., Shi, W., & Clarke, K.C.",
    journal: "International Journal of Applied Earth Observation and Geoinformation",
    volume: "32(1)",
    pages: "67-78",
    doi: "https://doi.org/10.1016/j.jag.2014.03.019",
    impactFactor: 4.650
  },
  {
    id: 79,
    type: "journal",
    year: 2014,
    title: "Local spectrum-trend similarity approach for detecting land-cover change by using SPOT-5 satellite images",
    authors: "Zhang, P., Lv, Z., & Shi, W.",
    journal: "IEEE Geoscience and Remote Sensing Letters",
    volume: "11(4)",
    pages: "738-742",
    doi: "https://doi.org/10.1109/LGRS.2013.2278202",
    impactFactor: 3.833
  },
  {
    id: 80,
    type: "journal",
    year: 2013,
    title: "Sub-pixel mapping based on BP neural network with multiple shifted remote sensing images",
    authors: "Shi, W.Z., Zhao, Y.L., & Wang, Q.M.",
    journal: "Journal of Infrared and Millimeter Waves",
    volume: "33(5)",
    pages: "527-532",
    doi: "https://doi.org/10.11972/j.1001-9014.2013.05.011",
    impactFactor: 0.355
  },
  {
    id: 81,
    type: "journal",
    year: 2013,
    title: "Analysis of spatial distribution pattern of change-detection error caused by misregistration",
    authors: "Shi, W., Hao, M.",
    journal: "International Journal of Remote Sensing",
    volume: "34(19)",
    pages: "6883-6897",
    doi: "https://doi.org/10.1080/01431161.2013.794644",
    impactFactor: 2.976
  },
  {
    id: 82,
    type: "journal",
    year: 2013,
    title: "Line segment confidence region-based string matching method for map conflation",
    authors: "Huh, Y., Yang, S., Ga, C., Yu, K., & Shi, W.",
    journal: "ISPRS Journal of Photogrammetry and Remote Sensing",
    volume: "78",
    pages: "69-84",
    doi: "https://doi.org/10.1016/j.isprsjprs.2013.01.005",
    impactFactor: 7.319
  },
  {
    id: 83,
    type: "journal",
    year: 2013,
    title: "A statistical simulation model for positional error of line features in geographic information systems",
    authors: "Tong, X.H., Sun, T., Fan, J., Goodchild, M.F., & Shi, W.Z.",
    journal: "International Journal of Applied Earth Observation and Geoinformation",
    volume: "21",
    pages: "136-148",
    doi: "https://doi.org/10.1016/j.jag.2012.09.005",
    impactFactor: 4.650
  },
  {
    id: 84,
    type: "journal",
    year: 2013,
    title: "Object-based spatial feature for classification of very high resolution remote sensing images",
    authors: "Zhang, P.L., Lv, Z.Y., & Shi, W.",
    journal: "IEEE Geoscience and Remote Sensing Letters",
    volume: "10(6)",
    pages: "1572-1576",
    doi: "https://doi.org/10.1109/LGRS.2013.2267890",
    impactFactor: 3.833
  },
  {
    id: 85,
    type: "journal",
    year: 2011,
    title: "Traffic flow data mining and evaluation based on fuzzy clustering techniques",
    authors: "Hu, C.C., Luo, N.A.X., Yan, X.H., & Shi, W.Z.",
    journal: "International Journal of Fuzzy Systems",
    volume: "13(4)",
    pages: "344-349",
    doi: "https://doi.org/10.1007/s10667-011-9876-9",
    impactFactor: 4.406
  },
  {
    id: 86,
    type: "journal",
    year: 2011,
    title: "A probability model-based method for land cover change detection using multi-spectral remotely sensed images",
    authors: "Shi, W., & Ding, H.Y.",
    journal: "Photogrammetrie Fernerkundung Geoinformation",
    volume: "(4)",
    pages: "271-280",
    doi: "https://doi.org/10.1127/1432-8364/2011/0088",
    impactFactor: 1.850
  },
  {
    id: 87,
    type: "journal",
    year: 2009,
    title: "A dynamic data model for mobile GIS",
    authors: "Shi, W., Kwan, K.W., Shea, G., & Cao, J.N.",
    journal: "Computers & Geosciences",
    volume: "35(11)",
    pages: "2210-2221",
    doi: "https://doi.org/10.1016/j.cageo.2009.03.002",
    impactFactor: 2.991
  },
  {
    id: 88,
    type: "journal",
    year: 2009,
    title: "A two-dimensional empirical mode decomposition method with application for fusing panchromatic and multispectral satellite images",
    authors: "Shi, W., Tian, Y., Huang, Y., Mao, H.X., & Liu, K.F.",
    journal: "International Journal of Remote Sensing",
    volume: "30(10)",
    pages: "2637-2652",
    doi: "https://doi.org/10.1080/01431160802555777",
    impactFactor: 2.976
  },
  {
    id: 89,
    type: "journal",
    year: 2009,
    title: "Adaptive mapped least squares SVM-based smooth fitting method for DSM generation of LIDAR data",
    authors: "Shi, W., Zheng, S., & Tian, Y.",
    journal: "International Journal of Remote Sensing",
    volume: "30(21)",
    pages: "5669-5683",
    doi: "https://doi.org/10.1080/01431160802709237",
    impactFactor: 2.976
  },
  {
    id: 90,
    type: "journal",
    year: 2008,
    title: "Dynamic routing model and solution methods for fleet management with mobile technologies",
    authors: "Cheung, B.K.S., Choy, K.L., Li, C.L., Shi, W.Z., & Tang, J.",
    journal: "International Journal of Production Economics",
    volume: "113(2)",
    pages: "694-705",
    doi: "https://doi.org/10.1016/j.ijpe.2007.10.018",
    impactFactor: 5.134
  },
  {
    id: 91,
    type: "journal",
    year: 2007,
    title: "Extended model of topological relations between spatial objects in geographic information systems",
    authors: "Liu, K.F., & Shi, W.Z.",
    journal: "International Journal of Applied Earth Observation and Geoinformation",
    volume: "9(3)",
    pages: "264-275",
    doi: "https://doi.org/10.1016/j.jag.2006.09.004",
    impactFactor: 4.650
  },
  {
    id: 92,
    type: "journal",
    year: 2006,
    title: "The Line-Based Transformation Model (LBTM) for image-to-image registration of high-resolution satellite image data",
    authors: "Shi, W., & Shaker, A.",
    journal: "International Journal of Remote Sensing",
    volume: "27(14)",
    pages: "3001-3012",
    doi: "https://doi.org/10.1080/01431160600607689",
    impactFactor: 2.976
  },
  {
    id: 93,
    type: "journal",
    year: 2005,
    title: "Uncertainties in Integrated Remote Sensing and GIS",
    authors: "Shi, W.Z., Ehlers, M., & Molenaar, M.",
    journal: "International Journal of Remote Sensing",
    volume: "26(14)",
    pages: "2911-2915",
    doi: "https://doi.org/10.1080/01431160512331376543",
    impactFactor: 2.976
  },
  {
    id: 94,
    type: "journal",
    year: 2004,
    title: "Modelling error propagation in vector-based overlay analysis",
    authors: "Shi, W.Z., Cheung, C.K., & Tong, X.H.",
    journal: "ISPRS Journal of Photogrammetry and Remote Sensing",
    volume: "59(1-2)",
    pages: "47-59",
    doi: "https://doi.org/10.1016/j.isprsjprs.2004.01.002",
    impactFactor: 7.319
  },
  {
    id: 95,
    type: "journal",
    year: 2004,
    title: "Theme issue: advanced techniques for analysis of geo-spatial data",
    authors: "Shi, W., Li, Z.L., & Bedard, Y.",
    journal: "ISPRS Journal of Photogrammetry and Remote Sensing",
    volume: "59(1-2)",
    pages: "1-5",
    doi: "https://doi.org/10.1016/j.isprsjprs.2004.01.001",
    impactFactor: 7.319
  },
  {
    id: 96,
    type: "journal",
    year: 2004,
    title: "Recent developments in modelling uncertainties in geo-spatial data and analysis",
    authors: "Shi, W.Z., Fisher, P.F., & Goodchild, M.F.",
    journal: "Photogrammetric Engineering and Remote Sensing",
    volume: "70(8)",
    pages: "919-920",
    doi: "https://doi.org/10.14358/PERS.70.8.919",
    impactFactor: 1.265
  },
  {
    id: 97,
    type: "journal",
    year: 2003,
    title: "A probabilistic paradigm for handling uncertain objects in GIS by randomized graph algebra",
    authors: "Shi, W., & Wu, H.Y.",
    journal: "Progress in Natural Science",
    volume: "13(9)",
    pages: "648-657",
    doi: "https://doi.org/10.1080/10020070312331344190",
    impactFactor: 1.099
  },
  {
    id: 98,
    type: "journal",
    year: 2003,
    title: "An object-oriented data model for complex objects in three-dimensional geographical information systems",
    authors: "Shi, W.Z., Yang, B.S., & Li, Q.Q.",
    journal: "International Journal of Geographical Information Science",
    volume: "17(5)",
    pages: "411-430",
    doi: "https://doi.org/10.1080/1365881031000086974",
    impactFactor: 3.733
  },
  {
    id: 99,
    type: "journal",
    year: 2003,
    title: "Modelling error propagation in vector-based buffer analysis",
    authors: "Shi, W.Z., Cheung, C.K., & Zhu, C.Q.",
    journal: "International Journal of Geographical Information Science",
    volume: "17(3)",
    pages: "251-271",
    doi: "https://doi.org/10.1080/1365881022000016007",
    impactFactor: 3.733
  },
  {
    id: 100,
    type: "journal",
    year: 2000,
    title: "Development of Voronoi-based cellular automata - an integrated dynamic model for Geographical Information Systems",
    authors: "Shi, W.Z., & Pang, M.Y.C.",
    journal: "International Journal of Geographical Information Science",
    volume: "14(5)",
    pages: "455-474",
    doi: "https://doi.org/10.1080/13658810050057597",
    impactFactor: 3.733
  },
  {
    id: 101,
    type: "journal",
    year: 1998,
    title: "A generic statistical approach for modelling error of geometric features in GIS",
    authors: "Shi, W.",
    journal: "International Journal of Geographical Information Science",
    volume: "12(2)",
    pages: "131-143",
    doi: "https://doi.org/10.1080/136588198241923",
    impactFactor: 3.733
  }
];